    version: '3.7'
    services:
      nginx:
        container_name: dev_web
        restart: on-failure
        #image: nginx:1.19.8
        build: 
          ./FrontEnd
        volumes:
          - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
          - static_volume:/app/static
        ports:
          - 82:82
        depends_on:
          - web
      web:
        container_name: dev_backend
        build: ./api_test
        restart: always
        env_file: dev.env
        command: bash -c "python manage.py runserver 0.0.0.0:7000 && python manage.py process_tasks"
        volumes:
         - .:/app
         - static_volume:/app/static
        depends_on:
         - db
        ports:
          - "7000:7000"
      db:
        container_name: dev_db
        image: postgres:12.0-alpine
        env_file: dev.env
        ports: 
          - "5432:5432"
        # volumes:
        #   - postgres_data:/var/lib/postgresql/data/
     
    
    volumes:
      static_volume:
      postgres_data: